repos:
  - repo: https://github.com/pycqa/isort  # Ordena tus importaciones
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^GUI/DISENO
        args: [ "--profile", "black" ]
  - repo: https://github.com/psf/black #  Reformatea el codigo
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^GUI/DISENO
        language_version: python3
        always_run: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
        exclude: "template.yaml"
      - id: debug-statements
      - id: pretty-format-json
        exclude: events/event.json
      - id: detect-private-key
      - id: fix-encoding-pragma
        args: [--remove]
  - repo: https://github.com/PyCQA/bandit #seguridad en scripts python
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: |
            (?x)^(
                GUI/LOGICA/socket_client.py|
                GUI/LOGICA/socket_server.py
            )$
  - repo: https://gitlab.com/pycqa/flake8 # Verifica el cumplimiento del código con PEP8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: |
            (?x)(
                ^tests/|
                ^GUI/DISENO/
            )
  - repo: https://github.com/hadialqattan/pycln # Encontrar y eliminar declaraciones de importación no utilizadas.
    rev: v1.3.2
    hooks:
      - id: pycln
  - repo: https://github.com/compilerla/conventional-pre-commit # Para verificar los mensajes de confirmación para el formato de confirmaciones convencionales
    rev: v1.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: []
default_language_version:
  python: python3.8.10
